pub const _0: usize = 0;
pub const _1: usize = 1;
pub const _2: usize = 2;
pub const _3: usize = 3;
pub const _4: usize = 4;
pub const _5: usize = 5;
pub const _6: usize = 6;
pub const _7: usize = 7;
pub const _8: usize = 8;
pub const _9: usize = 9;
pub const _A: usize = 10;
pub const _B: usize = 11;
pub const _C: usize = 12;
pub const _D: usize = 13;
pub const _E: usize = 14;
pub const _F: usize = 15;
pub const _G: usize = 16;
pub const _H: usize = 17;
pub const _I: usize = 18;
pub const _J: usize = 19;
pub const _K: usize = 20;
pub const _L: usize = 21;
pub const _M: usize = 22;
pub const _N: usize = 23;
pub const _O: usize = 24;
pub const _P: usize = 25;
pub const _Q: usize = 26;
pub const _R: usize = 27;
pub const _S: usize = 28;
pub const _T: usize = 29;
pub const _U: usize = 30;
pub const _V: usize = 31;
pub const _W: usize = 32;
pub const _X: usize = 33;
pub const _Y: usize = 34;
pub const _Z: usize = 35;
pub const ESCAPE: usize = 36;
pub const LSYSTEM: usize = 37;
pub const RSYSTEM: usize = 38;
pub const MENU: usize = 39;
pub const LBRACKET: usize = 40; // OEM_4
pub const RBRACKET: usize = 41; // OEM_6
pub const SEMICOLON: usize = 42; //OEM_1
pub const COMMA: usize = 43;
pub const PERIOD: usize = 44;
pub const QUOTE: usize = 45; //OEM_7
pub const SLASH: usize = 46; //OEM_2
pub const BACKSLASH: usize = 47; //OEM_5
pub const TILDE: usize = 48; //OEM_3
pub const EQUAL: usize = 49; //OEM_PLUS
pub const HYPHEN: usize = 50; //OEM_MINUS
pub const SPACE: usize = 51;
pub const ENTER: usize = 52; //RETURN
pub const BACKSPACE: usize = 53;
pub const TAB: usize = 54;
pub const PAGEUP: usize = 55; //VK_PRIOR
pub const PAGEDOWN: usize = 56; // NEXT
pub const END: usize = 57;
pub const HOME: usize = 58;
pub const INSERT: usize = 59;
pub const DELETE: usize = 60;
pub const ADD: usize = 61;
pub const SUBTRACT: usize = 62;
pub const MULTIPLY: usize = 63;
pub const DIVIDE: usize = 64;
pub const LEFT: usize = 65;
pub const RIGHT: usize = 66;
pub const UP: usize = 67;
pub const DOWN: usize = 68;
pub const NUMPAD_0: usize = 69;
pub const NUMPAD_1: usize = 70;
pub const NUMPAD_2: usize = 71;
pub const NUMPAD_3: usize = 72;
pub const NUMPAD_4: usize = 73;
pub const NUMPAD_5: usize = 74;
pub const NUMPAD_6: usize = 75;
pub const NUMPAD_7: usize = 76;
pub const NUMPAD_8: usize = 77;
pub const NUMPAD_9: usize = 78;
pub const F1: usize = 79;
pub const F2: usize = 80;
pub const F3: usize = 81;
pub const F4: usize = 82;
pub const F5: usize = 83;
pub const F6: usize = 84;
pub const F7: usize = 85;
pub const F8: usize = 86;
pub const F9: usize = 87;
pub const F10: usize = 88;
pub const F11: usize = 89;
pub const F12: usize = 90;
pub const F13: usize = 91;
pub const F14: usize = 92;
pub const F15: usize = 93;
pub const PAUSE: usize = 94;
pub const LSHIFT: usize = 95;
pub const RSHIFT: usize = 96;
pub const LCONTROL: usize = 97;
pub const RCONTROL: usize = 98;
pub const LALT: usize = 99;
pub const RALT: usize = 100;
pub const UNKNOWN: usize = 128;
// pub const F16 : usize                   = 67;
// pub const F17 : usize                   = 68;
// pub const F18 : usize                   = 69;
// pub const F19 : usize                   = 70;
// pub const F20 : usize                   = 71;
// pub const F21 : usize                   = 72;
// pub const F22 : usize                   = 73;
// pub const F23 : usize                   = 74;
// pub const F24 : usize                   = 75;
//pub const SEPARATOR : usize             = 48;
//pub const DECIMAL : usize               = 50;
// pub const CLEAR : usize                 = 82;
// pub const SHIFT : usize                 = 84;
// pub const CONTROL : usize               = 85;
// pub const CAPITAL : usize               = 88;
// pub const CONVERT : usize               = 90;
// pub const NONCONVERT : usize            = 91;
// pub const ACCEPT : usize                = 92;
// pub const MODECHANGE : usize            = 93;

// pub const SELECT : usize                = 103;
// pub const PRINT : usize                 = 104;
// pub const EXECUTE : usize               = 105;
// pub const SNAPSHOT : usize              = 106;

// pub const HELP : usize                  = 109;
// pub const LWIN : usize                  = 110;
// pub const RWIN : usize                  = 111;
// pub const APPS : usize                  = 112;
// pub const SLEEP : usize                 = 113;
// pub const NUMLOCK : usize               = 114;
// pub const SCROLL : usize                = 115;
// pub const LMENU : usize                 = 120;
// pub const RMENU : usize                 = 121;
// pub const BROWSER_BACK : usize          = 122;
// pub const BROWSER_FORWARD : usize       = 123;
// pub const BROWSER_REFRESH : usize       = 124;
// pub const BROWSER_STOP : usize          = 125;
// pub const BROWSER_SEARCH : usize        = 126;
// pub const BROWSER_FAVORITES : usize     = 127;
// pub const BROWSER_HOME : usize          = 128;
// pub const VOLUME_MUTE : usize           = 129;
// pub const VOLUME_DOWN : usize           = 130;
// pub const VOLUME_UP : usize             = 131;
// pub const MEDIA_NEXT_TRACK : usize      = 132;
// pub const MEDIA_PREV_TRACK : usize      = 133;
// pub const MEDIA_STOP : usize            = 134;
// pub const MEDIA_PLAY_PAUSE : usize      = 135;
// pub const LAUNCH_MAIL : usize           = 136;
// pub const LAUNCH_MEDIA_SELECT : usize   = 137;
// pub const LAUNCH_APP1 : usize           = 138;
// pub const LAUNCH_APP2 : usize           = 139;

// pub const OEM_8 : usize                 = 147;
// pub const OEM_102 : usize               = 148;
// pub const PROCESSKEY : usize            = 149;
// pub const PACKET : usize                = 150;
// pub const ATTN : usize                  = 151;
// pub const CRSEL : usize                 = 152;
// pub const EXSEL : usize                 = 153;
// pub const EREOF : usize                 = 154;
// pub const PLAY : usize                  = 155;
// pub const ZOOM : usize                  = 156;
// pub const NONAME : usize                = 157;
// pub const PA1 : usize                   = 158;
// pub const OEM_CLEAR : usize             = 159;
// pub const HANGUEL : usize               = 160;
// pub const HANGUL : usize                = 161;
// pub const IME_ON : usize                = 162;
// pub const JUNJA : usize                 = 163;
// pub const FINAL : usize                 = 164;
// pub const HANJA : usize                 = 165;
// pub const KANJI : usize                 = 166;
// pub const IME_OFF : usize               = 167;
// pub const CANCEL : usize                = 170;
// pub const UNKNOWN : usize               = 175;

pub mod action {
    pub const RELEASED: i32 = 0;
    pub const PRESSED: i32 = 1;
    pub const REPEAT: i32 = 2;
}
